const searchQuotes = [
  '"I will find you." -- Levi Ackerman',
  '"The answer is always closer than you think." -- Edward Elric',
  '"Seek and you shall find the truth." -- L Lawliet',
  '"Every search begins with a single step." -- Gon Freecss',
  '"I\'ll look everywhere until I find it!" -- Luffy',
  '"Keep looking. Don\'t settle." -- Spike Spiegel',
  '"You won\'t find what you don\'t search for." -- Erwin Smith',
  '"There\'s always more to discover." -- Deku',
  '"I\'ll track it down, no matter what." -- Killua Zoldyck',
  '"What are you looking for? I\'ll help." -- Tohru Honda',
  '"If you search with your heart, you\'ll find it." -- Naruto',
  '"Don\'t stop until you find it." -- Asta',
  '"The truth is out there." -- Conan Edogawa',
  '"Seek the unknown." -- Mob',
  '"Follow every lead." -- Lelouch',
  '"Hunting for the right one..." -- Hisoka',
  '"Looking for treasure?" -- Nami',
  '"Let me investigate." -- Senku',
  '"I can sense it nearby." -- Goku',
  '"My intuition says keep searching." -- Joseph Joestar',
  '"Data doesn\'t lie. Keep digging." -- Shikamaru',
  '"Even a fool can find what they seek." -- Vegeta',
  '"I\'ll find it with these eyes." -- Sasuke',
  '"The hunt continues." -- Kurapika',
  '"I detect something interesting." -- Bulma',
  '"Every answer hides in plain sight." -- Light Yagami',
  '"I shall locate it immediately." -- Sebastian',
  '"My nose never lies." -- Inuyasha',
  '"Let the search begin!" -- All Might',
  '"Processing... analyzing... found it!" -- Franky',
  '"Scanning all possibilities." -- Lain',
  '"The thing you seek is seeking you." -- Itachi',
  '"I\'ll comb every corner." -- Mikasa',
  '"My radar is picking something up!" -- Bulma',
  '"Follow the clues." -- Shinichi Kudo',
  '"I won\'t rest until I find it." -- Guts',
  '"Check every angle." -- Kakashi',
  '"I\'m on the trail." -- Saitama',
  '"Even in darkness, you can find light." -- Tanjiro',
  '"Look deeper." -- Aizen',
  '"Searching the archives..." -- Armin',
  '"Let\'s narrow it down." -- Senku',
  '"I have a lead!" -- Deku',
  '"Keep your eyes open." -- Zoro',
  '"Found something interesting?" -- Kisuke Urahara',
  '"I\'ll use all my senses." -- Nezuko',
  '"Precision in every search." -- Levi',
  '"The best finds are unexpected." -- Luffy',
  '"I deduce we\'re close." -- Conan',
  '"One step closer." -- Eren',
];

const recommendQuotes = [
  '"Trust me on this one." -- Luffy',
  '"I have excellent taste." -- Sanji',
  '"You\'ll love this, I promise." -- Gon',
  '"Let me show you something amazing." -- All Might',
  '"I think you\'d really like this." -- Tohru',
  '"My calculations say this is perfect." -- Senku',
  '"This one\'s a masterpiece." -- Jiraiya',
  '"You haven\'t seen THIS yet?!" -- Naruto',
  '"Allow me to recommend..." -- Sebastian',
  '"I picked this just for you." -- Killua',
  '"This will blow your mind." -- Kamina',
  '"A hidden gem awaits you." -- Deku',
  '"Believe in my taste!" -- Kamina',
  '"I\'ve curated the finest selection." -- Lelouch',
  '"Give this one a chance." -- Spike',
  '"An excellent choice awaits." -- Byakuya',
  '"You won\'t regret this." -- Goku',
  '"This changed my life." -- Mob',
  '"A personal favorite of mine." -- Kakashi',
  '"The perfect pick for you." -- Shikamaru',
  '"My heart says watch this." -- Asta',
  '"I\'ve seen thousands. This stands out." -- Levi',
  '"Pure gold, trust me." -- Edward Elric',
  '"You need this in your life." -- Megumin',
  '"I rarely recommend, but this..." -- Itachi',
  '"A true connoisseur\'s choice." -- Sanji',
  '"This will make you feel alive." -- Eren',
  '"I insist you try this one." -- Light',
  '"Perfection in anime form." -- Vegeta',
  '"My sixth sense says this is it." -- Joseph Joestar',
  '"You\'ll thank me later." -- Killua',
  '"Crafted to perfection." -- Tanjiro',
  '"I\'ve been saving this rec." -- Deku',
  '"An unforgettable experience." -- Guts',
  '"Start this immediately." -- L',
  '"My top shelf pick." -- Spike',
  '"A journey worth taking." -- Luffy',
  '"Tailored to your taste." -- Senku',
  '"This is the one." -- Saitama',
  '"Watch this next, no debate." -- Naruto',
  '"Absolutely elite." -- Zoro',
  '"I computed the optimal choice." -- Senku',
  '"A rare find." -- Conan',
  '"This deserves your attention." -- Erwin',
  '"Don\'t sleep on this one." -- Gojo',
  '"Adding this was fate." -- Homura',
  '"Nothing less than the best." -- All Might',
  '"Ready for something great?" -- Luffy',
  '"I vouch for this with my life." -- Kamina',
  '"Your next obsession." -- Hisoka',
];

const generalQuotes = [
  '"Believe it!" -- Naruto',
  '"Plus Ultra!" -- All Might',
  '"I\'ll take a potato chip... and eat it!" -- Light Yagami',
  '"People\'s dreams never end!" -- Blackbeard',
  '"The only one who can beat me is me." -- Aomine',
  '"Just who the hell do you think I am?!" -- Kamina',
  '"Bang." -- Spike Spiegel',
  '"In this world, is the destiny of mankind controlled by some transcendental entity?" -- Void',
  '"I am the bone of my sword." -- Archer',
  '"El Psy Kongroo." -- Okabe Rintaro',
  '"This is my ninja way." -- Naruto',
  '"Tatakae." -- Eren Yeager',
  '"One Punch is all I need." -- Saitama',
  '"Go beyond!" -- All Might',
  '"I\'ll surpass my limits!" -- Asta',
  '"Dattebayo!" -- Naruto',
  '"My drill will pierce the heavens!" -- Simon',
  '"I am here!" -- All Might',
  '"Omae wa mou shindeiru." -- Kenshiro',
  '"The night is darkest before the dawn." -- Itachi',
  '"Power comes in response to a need." -- Goku',
  '"If you don\'t take risks, you can\'t create a future." -- Luffy',
  '"Giving up is what kills people." -- Naruto',
  '"Hard work is worthless for those who don\'t believe in themselves." -- Naruto',
  '"Fear is not evil. It tells you what your weakness is." -- Gildarts',
  '"Whatever you lose, you\'ll find it again." -- Kenshin',
  '"A lesson without pain is meaningless." -- Edward Elric',
  '"Stand up and walk. Keep moving forward." -- Edward Elric',
  '"I don\'t want to conquer anything." -- Luffy',
  '"Surpass the impossible." -- Kamina',
  '"I am the hope of the universe." -- Goku',
  '"Zura ja nai, Katsura da!" -- Katsura',
  '"Your drill is the drill that will pierce the heavens!" -- Kamina',
  '"Even if I die, I can be replaced." -- Rei Ayanami',
  '"There\'s no shame in falling down." -- Midoriya',
  '"The world isn\'t perfect, but it\'s not that bad either." -- Roy Mustang',
  '"I\'ll never give up, that\'s my magic." -- Asta',
  '"I just keep moving forward." -- Eren',
  '"It\'s not the face that makes someone a monster." -- Goblin Slayer',
  '"To know sorrow is not terrifying." -- Gaara',
  '"An angel? No, I\'m a devil." -- Denji',
  '"Endure." -- Goblin Slayer',
  '"I have my friends." -- Natsu',
  '"A real man never dies, even when he is killed!" -- Kamina',
  '"I see now, this world is made of love." -- Emilia',
  '"Believe in yourself." -- Tanjiro',
  '"I am the man who will become Pirate King!" -- Luffy',
  '"With your dying will." -- Tsuna',
  '"If you can still stand, then fight." -- Zoro',
  '"The future is not set in stone." -- Okabe',
];

export type QuoteContext = 'search' | 'recommend' | 'general';

const quotePools: Record<QuoteContext, readonly string[]> = {
  search: searchQuotes,
  recommend: recommendQuotes,
  general: generalQuotes,
};

export function getRandomQuote(context: QuoteContext): string {
  const pool = quotePools[context];
  return pool[Math.floor(Math.random() * pool.length)];
}

