[[redirects]]
  from = "https://animetracker.lol/*"
  to = "https://www.animetracker.lol/:splat"
  status = 301
  force = true

[functions]
  directory = "netlify/functions"

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  CI = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
